sitewide_alert.settings:
  type: config_object
  label: 'Sitewide alert settings'
  constraints:
    FullyValidatable: ~
  mapping:
    show_on_admin:
      type: 'boolean'
      label: 'Show on Administration Pages'
    alert_styles:
      type: 'string'
      label: 'Available alert styles'
      constraints:
        Regex: '/^(.*)|(.*)$/'
    display_order:
      type: 'string'
      label: 'Display Order'
      constraints:
        AllowedValues: [ 'descending', 'ascending' ]
    automatic_refresh:
      type: 'boolean'
      label: 'Automatically update (Refresh) Alerts'
    refresh_interval:
      type: 'integer'
      label: 'Browser Refresh Interval (in seconds)'
      constraints:
        Range:
          min: 0
    cache_max_age:
      type: 'integer'
      label: 'Cache Max age (in seconds)'
      constraints:
        Range:
          min: 0
