<?php

/**
 * @file
 * Allows administrators to customize the libraries loaded on the site.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function libraries_provider_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.libraries_provider_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Libraries provider UI module provides an interface for managing libraries. A library is a collection of assets, which can be loaded in the frontend of the site</p>');
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Managing libraries') . '</dt>';
      $output .= '<dd>' . t('Users with the <em>Administer libraries</em> permission can edit settings for the custom libraries on the <a href=":library">libraries page</a>.', [
        ':library' => Url::fromRoute('entity.library.collection')->toString(),
      ]) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
