rest_api_authentication.settings:
  type: config_object
  label: Settings
  mapping:
    rest_api_authentication_customer_admin_email:
      type: string
    rest_api_authentication_license_key:
      type: string
    rest_api_authentication_customer_id:
      type: string
    rest_api_authentication_customer_admin_token:
      type: string
    rest_api_authentication_customer_api_key:
      type: string
    rest_api_authentication_status:
      type: string
    enable_authentication:
      type: integer
    authentication_method:
      type: integer
    api_token:
      type: string
