# Schema for the views plugins of the Registration module.

views.area.manage_registrations_caption:
  type: views_area
  label: 'Manage registrations caption'
views.area.manage_registrations_empty:
  type: views_area
  label: 'Manage registrations empty message'

views.argument.registration_host_entity_id:
  type: views_argument
  label: 'Host entity ID'
views.argument.registration_host_entity_type_id:
  type: views_argument
  label: 'Host entity type ID'

views.field.registration_host_entity:
  type: views_field
  label: 'Host entity'
views.field.registration_settings_operations:
  type: views_field
  label: 'Registration settings operations'
views.field.host_entity_registration_count:
  type: views_field
  label: 'Host entity registration count'
views.field.host_entity_spaces_remaining:
  type: views_field
  label: 'Host entity spaces remaining'
views.field.host_entity_spaces_reserved:
  type: views_field
  label: 'Host entity spaces reserved'

views.relationship.registration:
  type: views_relationship
  label: 'Registration'
views.relationship.registration_settings:
  type: views_relationship
  label: 'Registration settings'
