# Schema for the configuration files of the Libraries provider module.

libraries_provider.library.*:
  type: config_entity
  label: 'Library'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    source:
      type: string
      label: 'Source'
    version:
      type: string
      label: 'Source'
    enabled:
      type: boolean
      label: 'Enabled'
    minified:
      type: string
      label: 'Minified'
    variant:
      type: string
      label: 'Variant'
    replaces:
      type: sequence
      label: 'Replaces'
    custom_options:
      type: sequence
      label: 'Custom options'
